name: pigeon_example
description: Pigeon example

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.15.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  l: ^3.1.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  pigeon: ^1.0.12

flutter:
  uses-material-design: true